### ISSUE TITLE
Just a question. what is the theme in readme?

### ISSUE THREAD

**Issue by ytakzk** [fishery/shark#10]
could you tell me theme below in readme, if possible?

![image](https://cloud.githubusercontent.com/assets/7313406/13371154/491f74c4-dd62-11e5-94c6-a9b9f1ff2e36.png)

**Comment by bucaran** [comment]
That's Agnoster.

```
fisher install omf/theme-agnoster
```

Let me know if that works for you.

**Comment by ytakzk** [comment]
Thank you for letting me know! I installed the theme but it seems to be different from the colors above. Did you customize it a little bit? I am sorry for raising the unrelated comment to the library itself here.

![2016-02-27 16 10 20](https://cloud.githubusercontent.com/assets/7313406/13371560/a49da078-dd6c-11e5-9a5c-f68e5ae6b43b.png)

**Comment by bucaran** [comment]
Good. Now, you need to set the colors you like in your terminal application. 

I am using iTerm2 on OSX, so I press `cmd+,` which brings up the settings panel and I find my way from there. I am pretty sure whatever it is you are using there is something similar.

**Comment by ytakzk** [comment]
Cool! I downloaded the preset theme of Brogrammer from https://github.com/mbadolato/iTerm2-Color-Schemes and it is almost the same colors as yours.

Thanks a lot!

**Comment by bucaran** [comment]
I'm glad we like the same colors :smile:
